package com.abrastat.general

// Chance of occurring out of a factor of 256.
// 0 indicates that the effect will always occur.
enum class MoveEffect(private val target: Target, private val effectChance: Int) {
    NONE(Target.NONE, 0),
    CRITRATE(Target.SELF, 0),
    SLEEP(Target.OPPONENT, 0),
    PSN30(Target.OPPONENT, 76),
    PSN40(Target.OPPONENT, 102),
    PSN(Target.OPPONENT, 0),
    ABSORB(Target.OPPONENT, 0),
    BRN10(Target.OPPONENT, 25),
    BRN30(Target.OPPONENT, 75),
    FRZ10(Target.OPPONENT, 25),
    SELFDESTRUCT(Target.SELF, 0),
    DREAMEATER(Target.BOTH, 0),
    MIRRORMOVE(Target.BOTH, 0),
    SELF_ATTACKRAISE1(Target.SELF, 0),
    SELF_DEFENSERAISE1(Target.SELF, 0),
    SELF_SPATKRAISE1(Target.SELF, 0),
    SELF_EVASIONRAISE1(Target.SELF, 0),
    NEVERMISS(Target.SELF, 0),
    VITALTHROW(Target.SELF, 0),
    OPP_ATTACKDROP1(Target.OPPONENT, 0),
    OPP_DEFENSEDROP1(Target.OPPONENT, 0),
    PSYCHICSPDEFDROP(Target.OPPONENT, 0),
    CRUNCHSPDEFDROP(Target.OPPONENT, 0),
    ACIDSPDEFDROP(Target.OPPONENT, 0),
    OPP_SPEEDDROP1(Target.OPPONENT, 0),
    OPP_ACCURACYDROP1(Target.OPPONENT, 0),
    OPP_EVASIONDROP1(Target.OPPONENT, 0),
    HAZE(Target.BOTH, 0),
    BIDE(Target.SELF, 0),
    THRASH(Target.SELF, 0),
    ROAR(Target.OPPONENT, 0),
    MULTIHIT(Target.OPPONENT, 0),
    FLINCH10(Target.OPPONENT, 25),
    FLINCH30(Target.OPPONENT, 76),
    RECOVER(Target.SELF, 0),
    REST(Target.SELF, 0),
    TOXIC(Target.OPPONENT, 0),
    PAYDAY(Target.SELF, 0),
    LIGHTSCREEN(Target.SELF, 0),
    REFLECT(Target.SELF, 0),
    SAFEGUARD(Target.SELF, 0),
    TRIATTACK(Target.OPPONENT, 51),
    ONEHITKO(Target.OPPONENT, 0),
    RAZORWIND(Target.BOTH, 0),
    WRAP(Target.OPPONENT, 0),
    DOUBLEATTACK(Target.OPPONENT, 0),
    FOCUSENERGY(Target.SELF, 0),
    RECOIL25(Target.SELF, 0),
    RAGE(Target.SELF, 0),
    OPP_CONFUSION(Target.OPPONENT, 0),
    SELF_ATTACKRAISE2(Target.SELF, 0),
    SELF_DEFENSERAISE2(Target.SELF, 0),
    SELF_SPEEDRAISE2(Target.SELF, 0),
    SELF_SPDEFRAISE2(Target.SELF, 0),
    TRANSFORM(Target.SELF, 0),
    OPP_ATTACKDROP2(Target.OPPONENT, 0),
    OPP_DEFENSEDROP2(Target.OPPONENT, 0),
    OPP_SPEEDDROP2(Target.OPPONENT, 0),
    PRZ10(Target.OPPONENT, 25),
    PRZ30(Target.OPPONENT, 76),
    PRZ100(Target.OPPONENT, 255),
    PRZ(Target.OPPONENT, 0),
    SKYATTACK(Target.BOTH, 0),
    TWINNEEDLE(Target.OPPONENT, 51),
    SUBSTITUTE(Target.SELF, 0),
    HYPERBEAM(Target.SELF, 0),
    STRUGGLE(Target.SELF, 0),
    MIMIC(Target.SELF, 0),
    METRONOME(Target.SELF, 0),
    LEECHSEED(Target.SELF, 0),
    SPLASH(Target.NONE, 0),
    DISABLE(Target.OPPONENT, 0),
    SEISMICTOSS(Target.SELF, 0),
    PSYWAVE(Target.SELF, 0),
    CONVERSION2(Target.SELF, 0),
    LOCKON(Target.SELF, 0),
    SKETCH(Target.SELF, 0),
    SLEEPTALK(Target.SELF, 0),
    DESTINYBOND(Target.SELF, 0),
    FLAIL(Target.SELF, 0),
    SPITE(Target.OPPONENT, 0),
    FALSESWIPE(Target.OPPONENT, 0),
    QUICKATTACK(Target.SELF, 0),
    TRIPLEKICK(Target.OPPONENT, 85),
    THIEF(Target.OPPONENT, 255),
    MEANLOOK(Target.OPPONENT, 0),
    NIGHTMARE(Target.OPPONENT, 0),
    FLAMEWHEEL(Target.BOTH, 25),
    CURSE(Target.BOTH, 0),
    PROTECT(Target.SELF, 0),
    FORESIGHT(Target.OPPONENT, 0),
    PERISHSONG(Target.BOTH, 0),
    SANDSTORM(Target.BOTH, 0),
    ENDURE(Target.SELF, 0),
    ROLLOUT(Target.SELF, 0),
    SWAGGER(Target.OPPONENT, 0),
    FURYCUTTTER(Target.SELF, 0),
    ATTRACT(Target.OPPONENT, 0),
    RETURN(Target.SELF, 0),
    PRESENT(Target.SELF, 0),
    FRUSTRATION(Target.SELF, 0),
    SACREDFIRE(Target.BOTH, 127),
    MAGNITUDE(Target.OPPONENT, 0),
    BATONPASS(Target.SELF, 0),
    PURSUIT(Target.OPPONENT, 0),
    RAPIDSPIN(Target.SELF, 0),
    MORNINGSUN(Target.SELF, 0),
    SYNTHESIS(Target.SELF, 0),
    MOONLIGHT(Target.SELF, 0),
    HIDDENPOWER(Target.SELF, 0),
    RAINDANCE(Target.BOTH, 0),
    SUNNYDAY(Target.BOTH, 0),
    ANCIENTPOWER(Target.SELF, 25),
    BELLYDRUM(Target.SELF, 0),
    PSYCHUP(Target.BOTH, 0),
    MIRRORCOAT(Target.SELF, 0),
    SKULLBASH(Target.SELF, 0),
    TWISTER(Target.OPPONENT, 51),
    EARTHQUAKE(Target.OPPONENT, 0),
    FUTURESIGHT(Target.SELF, 0),
    GUST(Target.OPPONENT, 0),
    STOMP(Target.OPPONENT, 76),
    SOLARBEAM(Target.SELF, 0),
    THUNDER(Target.OPPONENT, 76),
    TELEPORT(Target.SELF, 0),
    BEATUP(Target.SELF, 0),
    FLY(Target.SELF, 0),
    DIG(Target.SELF, 0),
    DEFENSECURL(Target.SELF, 0),
    ENCORE(Target.OPPONENT, 0),
    CONFUSE100(Target.OPPONENT, 255),
    CURSE_GHOST(Target.BOTH, 0);

    enum class Target {
        SELF, OPPONENT, BOTH, NONE
    }

    fun target(): Target {
        return target
    }

    fun chance(): Int {
        return effectChance
    }
}