package com.abrastat.general;

import static com.abrastat.general.MoveEffect.Target.*;

// Chance of occurring out of a factor of 256.
// 0 indicates that the effect will always occur.

public enum MoveEffect {
    NONE(Target.NONE, 0),
    CRITRATE(SELF, 0),
    SLEEP(OPPONENT, 0),
    PSN30(OPPONENT, 76),
    PSN40(OPPONENT, 102),
    PSN(OPPONENT, 0),
    ABSORB(OPPONENT, 0),
    BRN10(OPPONENT, 25),
    FRZ10(OPPONENT, 25),
    SELFDESTRUCT(SELF, 0),
    DREAMEATER(BOTH, 0),
    MIRRORMOVE(BOTH, 0),
    SELF_ATTACKRAISE1(SELF, 0),
    SELF_DEFENSERAISE1(SELF, 0),
    SELF_SPATKRAISE1(SELF, 0),
    SELF_EVASIONRAISE1(SELF, 0),
    NEVERMISS(SELF, 0),
    VITALTHROW(SELF, 0),
    OPP_ATTACKDROP1(OPPONENT, 0),
    OPP_DEFENSEDROP1(OPPONENT, 0),
    PSYCHICSPDEFDROP(OPPONENT, 0),
    CRUNCHSPDEFDROP(OPPONENT, 0),
    ACIDSPDEFDROP(OPPONENT, 0),
    OPP_SPEEDDROP1(OPPONENT, 0),
    OPP_ACCURACYDROP1(OPPONENT, 0),
    OPP_EVASIONDROP1(OPPONENT, 0),
    HAZE(BOTH, 0),
    BIDE(SELF, 0),
    THRASH(SELF, 0),
    ROAR(OPPONENT, 0),
    MULTIATTACK(OPPONENT, 0),
    FLINCH10(OPPONENT, 25),
    FLINCH30(OPPONENT, 76),
    RECOVER(SELF, 0),
    REST(SELF, 0),
    TOXIC(OPPONENT, 0),
    PAYDAY(SELF, 0),
    LIGHTSCREEN(SELF, 0),
    REFLECT(SELF, 0),
    SAFEGUARD(SELF, 0),
    TRIATTACK(OPPONENT, 51),
    ONEHITKO(OPPONENT, 0),
    RAZORWIND(BOTH, 0),
    WRAP(OPPONENT, 0),
    DOUBLEATTACK(OPPONENT, 0),
    FOCUSENERGY(SELF, 0),
    RECOIL25(SELF, 0),
    RAGE(SELF, 0),
    OPP_CONFUSION(OPPONENT, 0),
    SELF_ATTACKRAISE2(SELF, 0),
    SELF_DEFENSERAISE2(SELF, 0),
    SELF_SPEEDRAISE2(SELF, 0),
    SELF_SPDEFRAISE2(SELF, 0),
    TRANSFORM(SELF, 0),
    OPP_ATTACKDROP2(OPPONENT, 0),
    OPP_DEFENSEDROP2(OPPONENT, 0),
    OPP_SPEEDDROP2(OPPONENT, 0),
    PRZ10(OPPONENT, 25),
    PRZ30(OPPONENT, 76),
    PRZ100(OPPONENT, 255),
    PRZ(OPPONENT, 0),
    SKYATTACK(BOTH, 0),
    TWINNEEDLE(OPPONENT, 51),
    SUBSTITUTE(SELF, 0),
    HYPERBEAM(SELF, 0),
    STRUGGLE(SELF, 0),
    MIMIC(SELF, 0),
    METRONOME(SELF, 0),
    LEECHSEED(SELF, 0),
    SPLASH(Target.NONE, 0),
    DISABLE(OPPONENT, 0),
    SEISMICTOSS(SELF, 0),
    PSYWAVE(SELF, 0),
    CONVERSION2(SELF, 0),
    LOCKON(SELF, 0),
    SKETCH(SELF, 0),
    SLEEPTALK(SELF, 0),
    DESTINYBOND(SELF, 0),
    FLAIL(SELF, 0),
    SPITE(OPPONENT, 0),
    FALSESWIPE(OPPONENT, 0),
    QUICKATTACK(SELF, 0),
    TRIPLEKICK(OPPONENT, 85),
    THIEF(OPPONENT, 255),
    MEANLOOK(OPPONENT, 0),
    NIGHTMARE(OPPONENT, 0),
    FLAMEWHEEL(BOTH, 25),
    CURSE(BOTH, 0),
    PROTECT(SELF, 0),
    FORESIGHT(OPPONENT, 0),
    PERISHSONG(BOTH, 0),
    SANDSTORM(BOTH, 0),
    ENDURE(SELF, 0),
    ROLLOUT(SELF, 0),
    SWAGGER(OPPONENT, 0),
    FURYCUTTTER(SELF, 0),
    ATTRACT(OPPONENT, 0),
    RETURN(SELF, 0),
    PRESENT(SELF, 0),
    FRUSTRATION(SELF, 0),
    SACREDFIRE(BOTH, 127),
    MAGNITUDE(OPPONENT, 0),
    BATONPASS(SELF, 0),
    PURSUIT(OPPONENT, 0),
    RAPIDSPIN(SELF, 0),
    MORNINGSUN(SELF, 0),
    SYNTHESIS(SELF, 0),
    MOONLIGHT(SELF, 0),
    HIDDENPOWER(SELF, 0),
    RAINDANCE(BOTH, 0),
    SUNNYDAY(BOTH, 0),
    ANCIENTPOWER(SELF, 25),
    BELLYDRUM(SELF, 0),
    PSYCHUP(BOTH, 0),
    MIRRORCOAT(SELF, 0),
    SKULLBASH(SELF, 0),
    TWISTER(OPPONENT, 51),
    EARTHQUAKE(OPPONENT, 0),
    FUTURESIGHT(SELF, 0),
    GUST(OPPONENT, 0),
    STOMP(OPPONENT, 76),
    SOLARBEAM(SELF, 0),
    THUNDER(OPPONENT, 76),
    TELEPORT(SELF, 0),
    BEATUP(SELF, 0),
    FLY(SELF, 0),
    DIG(SELF, 0),
    DEFENSECURL(SELF, 0),
    ENCORE(OPPONENT, 0),
    CONFUSE100(OPPONENT, 255),
    CURSE_GHOST(BOTH, 0);

    private Target target;
    private int effectChance;

    public enum Target {
        SELF,
        OPPONENT,
        BOTH,
        NONE
    }

    MoveEffect(Target target, int effectChance)   {
        this.target = target;
        this.effectChance = effectChance;
    }

    public Target target()   {
        return this.target;
    }

    public int chance() {
        return this.effectChance;
    }

}


